# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9f90e406e9752578962412a0a411fead"
name = "product-discount"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Added write_app_proxy so the app can configure an app proxy
scopes = "write_products,write_app_proxy"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

# Added App proxy config
[app_proxy]
# Route inside our Remix app that will actually handle the request
# (this is our existing API route)
url = "/api/product-discount"

# Path our storefront theme will call:
# /apps/product-discount â†’ proxied to /api/product-discount
prefix = "apps"
subpath = "product-discount"
